### ISSUE TITLE
Update Database

### ISSUE THREAD

**Issue by JustMe77** [Whitetigerswt/SAMP-geoip#6]
Hey, would you update once again the Databases? It's been a long time since the last update.

Regards

JustMe.77

**Comment by antoinefra** [comment]
@JustMe77 I can update them to the latest from Maxmind (august) and post them in few hours

**Comment by JustMe77** [comment]
@antoinefra That would be great!

**Comment by antoinefra** [comment]
@JustMe77 https://github.com/antoinefra/SAMP-geoip/releases
Remember to test before any real use

**Comment by spacemud** [comment]
@antoinefra Any chance you could reupload them? Your link appears to be dead.

**Comment by Jeroen52** [comment]
Perhaps we can automatically fetch the newest database every time one is released, convert it to a usable format and keep the usable format as artifacts for a couple months?

**Comment by spacemud** [comment]
Yeah, that would be good. Some instructions in the README with the method to convert the databases yourself would also be handy. Maybe even a script to do it for you?

**Comment by Jeroen52** [comment]
@spacemud Instruction have already been previously given, however those are not easily automated and use proprietary software.

**Comment by antoinefra** [comment]
@spacemud http://ovh.to/T8Np3fc I share again as it is only for 30 days MAX. Remember its august but always newer than old one. And test it before but it should work.

**Comment by spacemud** [comment]
@antoinefra Got them, many thanks.

**Comment by antoinefra** [comment]
@spacemud There is a guy who did it for much earlier called Silicium : http://forum.sa-mp.com/showthread.php?t=296171&page=13
